### ISSUE TITLE
Removing boilerplate

### ISSUE THREAD

**Issue by danroxha** [INSIS-s-Projects-ISEP/acme-monolithic-project#1]
# Improvement

The boilerplate mapping model to dto or  dto to model can be removed with ModelMapper library.

- model mapper: https://modelmapper.org/getting-started
- how to use(Portuguese video): https://youtu.be/HU7bfKG8nV4

**Comment by DavidGomesh** [comment]
> # Improvement
> The boilerplate mapping model to dto or dto to model can be removed with ModelMapper library.
> 
> * model mapper: https://modelmapper.org/getting-started
> * how to use(Portuguese video): https://youtu.be/HU7bfKG8nV4

Thanks for the tip. ModelMapper has been added to the project.
